COMMENT

   **************************************************
   File generated by: neuroConstruct v1.7.1 
   **************************************************


ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: Physiological Units

COMMENT
    ChannelML file based on Traub et al. 2003
ENDCOMMENT

    

? Creating ion concentration

TITLE Channel: cad

COMMENT
    An expontially decaying pool of calcium, with a ceiling concentration
ENDCOMMENT


UNITS {
    (mV) = (millivolt)
    (mA) = (milliamp)
    (um) = (micrometer)
    (l) = (liter)
    (molar) = (1/liter)
    (mM) = (millimolar)
}

    
NEURON {
    SUFFIX cad
    USEION ca READ ica WRITE cai VALENCE 2
    
    RANGE cai
    
    RANGE rest_conc
    
    
    RANGE beta
    
    
    GLOBAL total_current
    
    
    RANGE phi
    
    
}

ASSIGNED {

    ica (mA/cm2)
    diam (um)
}

INITIAL {
    cai = rest_conc

}

PARAMETER {

    total_current
    rest_conc = 0 (mM)
          
    
    beta = 0.01 (/ms)
   
    phi = 26000
    
}

STATE {

    cai (mM)

}

BREAKPOINT {

    SOLVE conc METHOD derivimplicit
    

}

DERIVATIVE conc {
    cai' = - (phi * ica) - ((cai - rest_conc)* beta)
    

}

