COMMENT

   **************************************************
   File generated by: neuroConstruct v1.7.1 
   **************************************************


ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: Physiological Units

COMMENT
    ChannelML file based on Traub et al. 2003
ENDCOMMENT

TITLE Channel: kc_fast

COMMENT
    Fast voltage and [Ca2+] dependent K conductance (BK channel). Based on NEURON port of FRB L2/3 model from Traub et al 2003. Same channel used in Traub et al 2005
ENDCOMMENT


UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (S) = (siemens)
    (um) = (micrometer)
    (molar) = (1/liter)
    (mM) = (millimolar)
    (l) = (liter)
}


    
NEURON {
      

    SUFFIX kc_fast
    USEION k READ ek WRITE ik VALENCE 1  ? reversal potential of ion is read, outgoing current is written
           
        
    USEION ca READ cai VALENCE 2 ? internal concentration of ion is read

    
    RANGE gmax, gion
    
    RANGE minf, mtau
    
    RANGE speedup_factor
}

PARAMETER { 
      

    gmax = 0.012 (S/cm2)  ? default value, should be overwritten when conductance placed on cell
    
    speedup_factor = 2 : Note units of this will be determined by its usage in the generic functions

}



ASSIGNED {
      

    v (mV)
    
    celsius (degC)
          

    ? Reversal potential of k
    ek (mV)
    ? The outward flow of ion: k calculated by rate equations...
    ik (mA/cm2)
          

    ? The internal concentration of ion: ca is used in the rate equations...
    cai (mM)   
    
    
    gion (S/cm2)
    minf
    mtau (ms)
    
}

BREAKPOINT { LOCAL g_factor, ca_conc
    

                        
    SOLVE states METHOD cnexp
         

    gion = gmax*((m)^1)
        
    ca_conc = cai / 1000000
    
    if (ca_conc < 0.00025 ) {
        g_factor =  (ca_conc / 0.00025) 
    } else {
        g_factor =  1
    }
    
    gion = gion * g_factor
          

    ik = gion*(v - ek)
            

}



INITIAL {
    
    ek = -95
        
    rates(v)
    m = minf
        
    
}
    
STATE {
    m
    
}

DERIVATIVE states {
    rates(v)
    m' = (minf - m)/mtau
    
}

PROCEDURE rates(v(mV)) {  
    
    ? Note: not all of these may be used, depending on the form of rate equations
    LOCAL  alpha, beta, tau, inf, gamma, zeta, temp_adj_m, A_alpha_m, B_alpha_m, Vhalf_alpha_m, A_beta_m, B_beta_m, Vhalf_beta_m
        
    TABLE minf, mtau
 DEPEND celsius, speedup_factor
 FROM -120 TO 140 WITH 1041
    
    
    UNITSOFF
    temp_adj_m = 1
    
            
                
           

        
    ?      ***  Adding rate equations for gate: m  ***
         
    ? Found a generic form of the rate equation for alpha, using expression: v < -10 ? speedup_factor * (2 / 37.95) * ( exp ( ((v + 50 ) / 11) - (( v + 53.5) / 27) ) ) : speedup_factor * 2 * (exp ( ( (-1 * v) - 53.5 ) / 27 ))
    
    
    if (v < -10 ) {
        alpha =  speedup_factor * (2 / 37.95) * ( exp ( ((v + 50 ) / 11) - (( v + 53.5) / 27) ) ) 
    } else {
        alpha =  speedup_factor * 2 * (exp ( ( (-1 * v) - 53.5 ) / 27 ))
    }
     
    ? Found a generic form of the rate equation for beta, using expression: v < -10 ? speedup_factor * 2 * (exp ( ( (-1 * v) - 53.5 ) / 27 )) - alpha : speedup_factor * 0.0
    
    
    if (v < -10 ) {
        beta =  speedup_factor * 2 * (exp ( ( (-1 * v) - 53.5 ) / 27 )) - alpha 
    } else {
        beta =  speedup_factor * 0.0
    }
    mtau = 1/(temp_adj_m*(alpha + beta))
    minf = alpha/(alpha + beta)
          
       
    
    ?     *** Finished rate equations for gate: m ***
    

         

}


UNITSON


