COMMENT

   **************************************************
   File generated by: neuroConstruct v1.7.1 
   **************************************************


ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: Physiological Units

COMMENT
    ChannelML file based on Traub et al. 2003
ENDCOMMENT

TITLE Channel: naf

COMMENT
    Fast Sodium transient (inactivating) current. Based on NEURON port of FRB L2/3 model from Traub et al 2003. Same channel used in Traub et al 2005
ENDCOMMENT


UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (S) = (siemens)
    (um) = (micrometer)
    (molar) = (1/liter)
    (mM) = (millimolar)
    (l) = (liter)
}


    
NEURON {
      

    SUFFIX naf
    USEION na READ ena WRITE ina VALENCE 1  ? reversal potential of ion is read, outgoing current is written
           
        
    RANGE gmax, gion
    
    RANGE minf, mtau
    
    RANGE hinf, htau
    
    RANGE fastNa_shift
    RANGE a
    RANGE b
    RANGE c
    RANGE d
}

PARAMETER { 
      

    gmax = 0.1875 (S/cm2)  ? default value, should be overwritten when conductance placed on cell
    
    fastNa_shift = 0 : Note units of this will be determined by its usage in the generic functions

    a = 0 : Note units of this will be determined by its usage in the generic functions

    b = 0 : Note units of this will be determined by its usage in the generic functions

    c = 0 : Note units of this will be determined by its usage in the generic functions

    d = 0 : Note units of this will be determined by its usage in the generic functions

}



ASSIGNED {
      

    v (mV)
    
    celsius (degC)
          

    ? Reversal potential of na
    ena (mV)
    ? The outward flow of ion: na calculated by rate equations...
    ina (mA/cm2)
    
    
    gion (S/cm2)
    minf
    mtau (ms)
    hinf
    htau (ms)
    
}

BREAKPOINT { 
                        
    SOLVE states METHOD cnexp
         

    gion = gmax*((m)^3)*((h)^1)      

    ina = gion*(v - ena)
            

}



INITIAL {
    
    ena = 50
        
    rates(v)
    m = minf
        h = hinf
        
    
}
    
STATE {
    m
    h
    
}

DERIVATIVE states {
    rates(v)
    m' = (minf - m)/mtau
    h' = (hinf - h)/htau
    
}

PROCEDURE rates(v(mV)) {  
    
    ? Note: not all of these may be used, depending on the form of rate equations
    LOCAL  alpha, beta, tau, inf, gamma, zeta, temp_adj_m, A_tau_m, B_tau_m, Vhalf_tau_m, A_inf_m, B_inf_m, Vhalf_inf_m, temp_adj_h, A_tau_h, B_tau_h, Vhalf_tau_h, A_inf_h, B_inf_h, Vhalf_inf_h
        
    TABLE minf, mtau,hinf, htau
 DEPEND celsius, fastNa_shift, a, b, c, d
 FROM -120 TO 60 WITH 741
    
    
    UNITSOFF
    temp_adj_m = 1
    temp_adj_h = 1
    
            
                
           

        
    ?      ***  Adding rate equations for gate: m  ***
         
    ? Found a generic form of the rate equation for tau, using expression: (v + fastNa_shift) < -30 ? 0.025 + 0.14 * ( exp ( ((v + fastNa_shift) + 30) / 10) ) : 0.02 + a + (0.145 + b) * ( exp ( -1 * ((v + fastNa_shift + d) + 30) / (10.0 + c)) )
    
    
    if ((v + fastNa_shift) < -30 ) {
        tau =  0.025 + 0.14 * ( exp ( ((v + fastNa_shift) + 30) / 10) ) 
    } else {
        tau =  0.02 + a + (0.145 + b) * ( exp ( -1 * ((v + fastNa_shift + d) + 30) / (10.0 + c)) )
    }
    mtau = tau/temp_adj_m
     
    ? Found a generic form of the rate equation for inf, using expression:  1 / ( 1 + (exp ( ( -1 * (v + fastNa_shift) - 38) / 10)) ) 
    inf =  1 / ( 1 + (exp ( ( -1 * (v + fastNa_shift) - 38) / 10)) ) 
        
    minf = inf
          
       
    
    ?     *** Finished rate equations for gate: m ***
    

    
            
                
           

        
    ?      ***  Adding rate equations for gate: h  ***
         
    ? Found a generic form of the rate equation for tau, using expression: 0.15 + 1.15 / ( 1 + ( exp (( ( v + fastNa_shift * 0 ) + 37 ) / 15) ) )
    tau = 0.15 + 1.15 / ( 1 + ( exp (( ( v + fastNa_shift * 0 ) + 37 ) / 15) ) )
        
    htau = tau/temp_adj_h
     
    ? Found a generic form of the rate equation for inf, using expression: 1 / ( 1 + (exp (( ( v + fastNa_shift * 0 ) + 62.9 ) / 10.7)) )
    inf = 1 / ( 1 + (exp (( ( v + fastNa_shift * 0 ) + 62.9 ) / 10.7)) )
        
    hinf = inf
          
       
    
    ?     *** Finished rate equations for gate: h ***
    

         

}


UNITSON


