COMMENT

   **************************************************
   File generated by: neuroConstruct v1.7.1 
   **************************************************


ENDCOMMENT


?  This is a NEURON mod file generated from a ChannelML file

?  Unit system of original ChannelML file: Physiological Units

COMMENT
    ChannelML file based on Traub et al. 2003
ENDCOMMENT

TITLE Channel: napf_spinstell

COMMENT
    Fast Sodium transient (inactivating) current. Based on activating component of naf from Traub et al 2005
ENDCOMMENT


UNITS {
    (mA) = (milliamp)
    (mV) = (millivolt)
    (S) = (siemens)
    (um) = (micrometer)
    (molar) = (1/liter)
    (mM) = (millimolar)
    (l) = (liter)
}


    
NEURON {
      

    SUFFIX napf_spinstell
    USEION na READ ena WRITE ina VALENCE 1  ? reversal potential of ion is read, outgoing current is written
           
        
    RANGE gmax, gion
    
    RANGE minf, mtau
    
    RANGE sh
    RANGE a
    RANGE b
    RANGE c
    RANGE d
}

PARAMETER { 
      

    gmax = 0.0032 (S/cm2)  ? default value, should be overwritten when conductance placed on cell
    
    sh = -2.5 : Note units of this will be determined by its usage in the generic functions

    a = 0 : Note units of this will be determined by its usage in the generic functions

    b = 0 : Note units of this will be determined by its usage in the generic functions

    c = 0 : Note units of this will be determined by its usage in the generic functions

    d = 0 : Note units of this will be determined by its usage in the generic functions

}



ASSIGNED {
      

    v (mV)
    
    celsius (degC)
          

    ? Reversal potential of na
    ena (mV)
    ? The outward flow of ion: na calculated by rate equations...
    ina (mA/cm2)
    
    
    gion (S/cm2)
    minf
    mtau (ms)
    
}

BREAKPOINT { 
                        
    SOLVE states METHOD cnexp
         

    gion = gmax*((m)^3)      

    ina = gion*(v - ena)
            

}



INITIAL {
    
    ena = 50
        
    rates(v)
    m = minf
        
    
}
    
STATE {
    m
    
}

DERIVATIVE states {
    rates(v)
    m' = (minf - m)/mtau
    
}

PROCEDURE rates(v(mV)) {  
    
    ? Note: not all of these may be used, depending on the form of rate equations
    LOCAL  alpha, beta, tau, inf, gamma, zeta, temp_adj_m, A_tau_m, B_tau_m, Vhalf_tau_m, A_inf_m, B_inf_m, Vhalf_inf_m
        
    TABLE minf, mtau
 DEPEND celsius, sh, a, b, c, d
 FROM -120 TO 60 WITH 741
    
    
    UNITSOFF
    temp_adj_m = 1
    
            
                
           

        
    ?      ***  Adding rate equations for gate: m  ***
         
    ? Found a generic form of the rate equation for tau, using expression: ( v + sh ) < -30 ? 0.025 + 0.14 * ( exp ( ((v + sh) + 30) / 10) ) : 0.02 + a + (0.145 + b) * ( exp ( -1 * ((v + sh + d) + 30) / (10 + c)) )
    
    
    if (( v + sh ) < -30 ) {
        tau =  0.025 + 0.14 * ( exp ( ((v + sh) + 30) / 10) ) 
    } else {
        tau =  0.02 + a + (0.145 + b) * ( exp ( -1 * ((v + sh + d) + 30) / (10 + c)) )
    }
    mtau = tau/temp_adj_m
     
    ? Found a generic form of the rate equation for inf, using expression:  1 / ( 1 + (exp ( ( -1 * (v + sh) - 38) / 10)) ) 
    inf =  1 / ( 1 + (exp ( ( -1 * (v + sh) - 38) / 10)) ) 
        
    minf = inf
          
       
    
    ?     *** Finished rate equations for gate: m ***
    

         

}


UNITSON


